config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  post 'books/:id/reserve', to: 'books#reserve', as: 'reserve_book'
  post 'books/:id/unreserve', to: 'books#unreserve', as: 'unreserve_book'
  post 'books/:id/pay', to: 'books#pay', as: 'pay_book'
  post 'books/:id/unpay', to: 'books#unpay', as: 'unpay_book'

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true

  enum state: %i[unreserved reserved paid]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def to_s
    email;
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy reserve unreserve pay unpay ]
  before_action :authenticate_user!

  # GET /books or /books.json
  def index
    @books = Book.all
    @books.each do |b|
      b.unreserved! if b.reserved?
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  def reserve
    if @book.unreserved?
      @book.reserved!
      @book.user = current_user
    end
    
    respond_to do |format|
      if @book.save
        format.js
      end
    end
  end

  def unreserve
    if @book.user == current_user
      if @book.reserved?
        @book.unreserved!
        @book.user = nil
      end
      
      respond_to do |format|
        if @book.save
          format.js
        end
      end
    end
  end

  def pay
    if @book.user == current_user
      @book.paid!

      respond_to do |format|
        if @book.save
          format.js
        end
      end
    end
  end

  def unpay
    if @book.user == current_user
      @book.unreserved!

      respond_to do |format|
        if @book.save
          format.js
        end
      end
    end
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :user_id, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr id=<%= "row-book-#{book.id}" %> class=<%= book.reserved? ? 'book_reserved' : 'book'%>>
  <td><%= book.id %></td>
  <td><%= book.author %></td>
  <td><%= book.title %></td>
  <td id=<%= "user-book-#{book.id}" %>><%= book.user %></td>
  <td id=<%= "state-book-#{book.id}" %>><%= book.state %></td>
  <td>
    <%= link_to(book.unreserved? ? 'Reserve' : '', reserve_book_path(book), id: "bt-reserve-#{book.id}", remote: true, method: :post) %>
    <%= link_to('', pay_book_path(book), id: "bt-pay-#{book.id}", remote: true, method: :post) %>
    <%= link_to(book.paid? ? 'Return' : '', unpay_book_path(book), id: "bt-unpay-#{book.id}", remote: true, method: :post, data: { confirm: 'Are you sure?' }) %>
  </td>
  <td id=<%= "timeout-book-#{book.id}" %>></td>
</tr>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.number_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Author</th>
      <th>Title</th>
      <th>User</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @books %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/pay.js.erb
// select nodes
txtState = document.querySelector("#state-book-" + "<%= @book.id %>");
btReserve = document.querySelector("#bt-reserve-" + "<%= @book.id %>");
row = document.querySelector("#row-book-" + "<%= @book.id %>");
txtTimeout = document.querySelector("#timeout-book-" + "<%= @book.id %>");
btPay = document.querySelector("#bt-pay-" + "<%= @book.id %>");
btUnpay = document.querySelector("#bt-unpay-" + "<%= @book.id %>");

txtState.innerText = "<%= @book.state %>";

<% if @book.paid? %>
  txtTimeout.remove();
  btReserve.innerText = "";
  btPay.innerText = "";
  btUnpay.innerText = "Return";
  row.classList.remove("book_reserved");
  row.classList.add("book_paid");
<% end %>

app/views/books/reserve.js.erb
// select nodes
txtState = document.querySelector("#state-book-" + "<%= @book.id %>");
btReserve = document.querySelector("#bt-reserve-" + "<%= @book.id %>");
row = document.querySelector("#row-book-" + "<%= @book.id %>");
txtTimeout = document.querySelector("#timeout-book-" + "<%= @book.id %>");
txtUser = document.querySelector("#user-book-" + "<%= @book.id %>");
btPay = document.querySelector("#bt-pay-" + "<%= @book.id %>");
btUnpay = document.querySelector("#bt-unpay-" + "<%= @book.id %>");

function getTimeString(seconds) {
  let mins = Math.floor(seconds / 60);
  let secs = seconds - mins * 60;

  return ("00" + mins).slice(-2) + ":" + ("00" + secs).slice(-2);
}

function displayTimer(timeout) {
  let txtTimeout = document.querySelector("#timeout-book-" + "<%= @book.id %>");
  let end = timeout/1000;

  if (end > 0) {
    let ticker = setInterval(function() {
      end--;
      if (end <= 0 || !txtTimeout) {
        clearInterval(ticker);
      } else {
        txtTimeout.innerText = getTimeString(end);
      }

    }, 1000);
  }
}

function getHeaders() {
  let headers = new window.Headers({
    'Accept': 'application/javascript',
    'X-Requested-With': 'XMLHttpRequest'
  })

  const csrfToken = document.head.querySelector("[name='csrf-token']").getAttribute("content");
  if (csrfToken) { headers.append('X-CSRF-Token', csrfToken); }

  return headers
}

function createRequest(url, method = 'get') {
  const request = new window.Request(url, {
    headers: getHeaders(),
    method: method,
    credentials: 'same-origin'
  })
  return request
}

function setupTimer() {
  timeout = 120000;
  displayTimer(timeout);
  txtTimeout.innerText = getTimeString(timeout / 1000);

  setTimeout(function() {
    let txt = document.querySelector("#timeout-book-" + "<%= @book.id %>");
    if (txt) {
      txt.innerText = "Timeout expired :(";
    }
    // call book#unreserve via API
    fetch(createRequest("books/" + "<%= @book.id %>" + "/unreserve", 'POST')).then(v => {
      v.text().then(txt => {
        eval(txt);
      })
    })
  }, timeout);
}

// refresh state text
txtState.innerText = "<%= @book.state %>";
txtUser.innerText = "<%= @book.user %>";

// refresh texts and show/hide nodes based on status
<% if @book.reserved? %>
  btReserve.innerText = "";
  row.classList.add("book_reserved");
  btPay.innerText = "Pay";
  btUnpay.innerText = "";
  setupTimer();
<% end %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @book.user_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @book.state %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/unpay.js.erb
// select nodes
txtState = document.querySelector("#state-book-" + "<%= @book.id %>");
btReserve = document.querySelector("#bt-reserve-" + "<%= @book.id %>");
row = document.querySelector("#row-book-" + "<%= @book.id %>");
txtTimeout = document.querySelector("#timeout-book-" + "<%= @book.id %>");
btPay = document.querySelector("#bt-pay-" + "<%= @book.id %>");
btUnpay = document.querySelector("#bt-unpay-" + "<%= @book.id %>");

txtState.innerText = "<%= @book.state %>";

<% if @book.unreserved? %>
  btReserve.innerText = "Reserve";
  btPay.innerText = "";
  btUnpay.innerText = "";
  row.classList.remove("book_paid");
  row.classList.remove("book_reserved");
<% end %>

app/views/books/unreserve.js.erb
// select nodes
txtState = document.querySelector("#state-book-" + "<%= @book.id %>");
btReserve = document.querySelector("#bt-reserve-" + "<%= @book.id %>");
row = document.querySelector("#row-book-" + "<%= @book.id %>");
txtTimeout = document.querySelector("#timeout-book-" + "<%= @book.id %>");
txtUser = document.querySelector("#user-book-" + "<%= @book.id %>");
btPay = document.querySelector("#bt-pay-" + "<%= @book.id %>");
btUnpay = document.querySelector("#bt-unpay-" + "<%= @book.id %>");

// refresh state text
txtState.innerText = "<%= @book.state %>";
txtUser.innerText = "<%= @book.user %>";

// refresh texts and show/hide nodes based on status
<% if @book.unreserved? %>
  txtTimeout.innerText = "";
  btReserve.innerText = "Reserve";
  row.classList.remove("book_reserved");
  btPay.innerText = "";
  btUnpay.innerText = "";
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to 'Book portal', root_path, class: 'navbar-header' %>
  <span class="navbar-separator"></span>
  <span class="navbar-group-right">
    <% if signed_in? %>
      <%= link_to 'My profile', edit_user_registration_path, class: 'navbar-link' %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'navbar-link' %>
    <% else %>    
      <%= link_to 'Sign in', new_user_session_path, class: 'navbar-link' %>
      <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-link' %>
    <% end %>
  </span>
</div>